---
title: "About"
subtitle: "Who we are, where we are from, and what we do"
---

[R-Ladies](https://rladies.org/) began as a meetup group in San Francisco in 2012 when `Gabriela de Queiroz` founded the first chapter and organized the first event. Over the next three years, three more groups started following this example. After the useR! conference in 2016, where Gabriela and other organizers met in person, `R-Ladies Global` was co-founded by several active community members. Since then, the organization has experienced massive and rapid growth, with the number of R-Ladies chapters increasing significantly. Today, R-Ladies has 218 chapters in 29 countries and over 3943 events contributing to promote gender diversity in the `R community`.

> `R-Ladies Rome` has two organizers: [Federica Gazzelloni](https://federicagazzelloni.netlify.app/) and [Katie Wood](https://www.linkedin.com/in/katie-wood-omca%E2%84%A2-92060817/). Federica is a statistician and actuary who works as an independent researcher. She is passionate about data visualization and the R programming language. Katie is an experienced marketing manager with a background in various industry sectors across global markets.

To get in touch with R-Ladies Rome, you can email us at [rome\@rladies.org](mailto:rome@rladies.org){.email}, follow us on Twitter at [\@rladiesrome](https://twitter.com/RLadiesRome), and check out our GitHub account at [meetup-presentations_rome](https://www.meetup.com/rladies-rome/). We welcome contributions from anyone interested in promoting gender diversity in the R community. You can contribute by attending our meetups, sharing your knowledge and insights, and helping us organize events.

We have a [code of conduct](https://rladies.org/coc/) that all members and participants are expected to follow. The code of conduct is designed to ensure that our community is a safe and welcoming space for everyone. You can find the code of conduct on our GitHub page. We take any violations of the code of conduct seriously and will take appropriate action to address them.
