---
title: "Overview"
subtitle: "What is going on at `R-Ladies Rome`? Check out our upcoming events!"
#listing:
#  contents: 2023/meetup
#  sort: "date desc"
#  type: grid
#  image-height: "200"
#  categories: false
page-layout: full
title-block-banner: false
sidebar: true
editor: 
  markdown: 
    wrap: 72
---
\

Throughout the year, `R-Ladies Rome` has hosted a series of engaging events focused on empowering women in data science and technology. The lineup included `workshops` and `talks` on essential topics such as reproducible publications, data wrangling, and interactive dashboards, featuring expert speakers from the `Open Source community`.

These sessions fostered learning and collaboration, providing attendees with `valuable insights` and `hands-on experience`. Looking ahead, the community continues to plan exciting events that promote knowledge sharing and skill development among participants.

## Upcoming Events

**October 30: Open Source Software in Government**
[Gwynn Gebeyehu](https://www.linkedin.com/in/gwynn-gebeyehu-83694280/) will discuss the role of open-source software in government. 
`RSVP`: <https://www.meetup.com/rladies-rome/events/303989623>

**November 18: Session with Julia Stewart Lowndes**
[Julia Stewart Lowndes](https://www.linkedin.com/in/julia-stewart-lowndes/) will lead an engaging session on a topic to be announced.
`RSVP`: <https://www.meetup.com/rladies-rome/events/303646680>

**December 10: Using Copilot and R**
[Yanina Bellini Saibene](https://www.linkedin.com/in/yabellini/) will share insights on using Copilot and R.
`RSVP`: <https://www.meetup.com/rladies-rome/events/303989815>

**Featuring: January Session**
[Eli Holder](https://www.linkedin.com/in/eliholder/) will lead a session in January. Stay tuned for more details!

## Past Events

[**January: Introduction to Reproducible Publications with Quarto**](https://rladiesrome.org/talks/2024/meetup/01162024/)

Our inaugural event featured Dr. [Torin
White](https://www.linkedin.com/in/torinwhite/), who provided valuable
insights into creating reproducible documents using Quarto. Attendees
learned essential techniques for combining code, analysis, and narrative to enhance their research projects.

**February: Building a Chatbot with OpenAI, Shiny & R**

Next up, we are excited to partner with the [TunisR User
Group](https://www.meetup.com/tunis-r-user-group/) for an interactive
workshop on building chatbots with OpenAI and Shiny. Led by [James
Wade](https://www.linkedin.com/in/james-h-wade/), participants will
explore the possibilities of conversational AI and learn how to develop
their own chatbot applications.

[**February: Unraveling the Mysteries of Debugging in R**](https://rladiesrome.org/talks/2024/meetup/02202024/)

Join us for a session with [Shannon
Pileggi](https://www.linkedin.com/in/shannon-m-pileggi/) as she shares
essential tips and techniques for debugging R code. Whether you're a
beginner or an experienced R user, this workshop will equip you with the
skills to troubleshoot and resolve common programming errors.

[**March: Extending the Data Science Workflow: {vetiver} and {pins}**](https://rladiesrome.org/talks/2024/meetup/03222024/)

In March, [Isabel
Zimmerman](https://www.linkedin.com/in/isabel-zimmerman/) will lead a
discussion on the Vetiver and Pins packages, offering valuable insights
into their applications and functionalities. Don't miss this opportunity
to dive deep into these powerful tools for data management and
visualization.

[**April: R for Geospatial Data Science and Public Health Surveillance**](https://rladiesrome.org/talks/2024/meetup/04162024/)

Geospatial health data play a crucial role in informing public health and policy by revealing geographic and temporal patterns, identifying risk factors, and detecting outbreaks swiftly. In this talk, [Paula Moraga](https://www.paulamoraga.com/), Assistant Professor of Statistics at KAUST, will provide an overview of R packages and statistical methods for geospatial data analysis and health surveillance, addressing data biases and availability issues. 

[**May: R in Production, An Evening with Dr. Hadley Wickham**](https://rladiesrome.org/talks/2024/meetup/05242024/)

Save the date for a special event with [Dr. Hadley
Wickham](https://www.linkedin.com/in/hadleywickham/), renowned R
developer and author. In collaboration with [R-Ladies NYC](https://www.meetup.com/rladiesnyc) this session will be with one of the leading figures in the R community. Dr. Wickham will share his insights on deploying R in production environments and discuss best practices for scaling data science projects.

[**June: Building a Website in R**](https://rladiesrome.org/talks/2024/meetup/06282024/)

In collaboration with [R-Ladies NYC](https://www.meetup.com/rladiesnyc), we are excited to present a workshop on building websites in R. Led by [Federica Gazzelloni](https://www.linkedin.com/in/federicagazzelloni/), this session will cover essential tools and techniques for creating interactive web applications using R Markdown and Shiny.

[**Mid-July: Quarto Dashboards**](https://rladiesrome.org/talks/2024/meetup/07182024/)

Join us for a session with [Isabella Velasquez](https://www.linkedin.com/in/ivelasq/), who will demonstrate how to create interactive dashboards with Quarto. Learn how to leverage the power of Quarto to build dynamic visualizations and share your insights with others.

[**Late-July: Reproducible Environments with Docker**](https://rladiesrome.org/talks/2024/meetup/07292924/)

In this workshop, [Bruno Rodrigues](https://www.linkedin.com/in/brodriguesco/) will guide participants through the process of creating reproducible environments using Docker. Gain hands-on experience with Docker containers and learn how to streamline your data science workflows.

[**September: Data Wrangling Practice with R**](https://rladiesrome.org/talks/2024/meetup/09302024/)

This hands-on session is lead by [Federica Gazzelloni](https://federicagazzelloni.com/), **R-Ladies Rome** Organizer. Data wrangling offers a practical and comprehensive guide to mastering data cleaning, manipulation, and transformation. This session walks you through essential techniques that are key to any data science or data analysis workflow.

\

Stay tuned for more exciting events and collaborations as we continue
our journey of learning and empowerment at **R-Ladies Rome**!

*Have questions or suggestions for future events? Feel free to reach out
to us!* 👉<rome@rladies.org>
